// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void lv_demo_stress(lv_event_t * e);
void lv_demo_benchmark(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
