// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "ui.h"

void lv_demo_benchmark(lv_event_t * e)
{
	// Your code here
}

void lv_demo_stress(lv_event_t * e)
{
	// Your code here
}
