// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image6, &ui_img_image01_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button10 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_Button10, 100);
    lv_obj_set_height(ui_Button10, 80);
    lv_obj_set_x(ui_Button10, -350);
    lv_obj_set_y(ui_Button10, -200);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Button10, &ui_img_1470773777, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button11 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_Button11, 100);
    lv_obj_set_height(ui_Button11, 80);
    lv_obj_set_x(ui_Button11, 350);
    lv_obj_set_y(ui_Button11, -200);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button11, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button11, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Button11, &ui_img_851485880, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);

}
